import './globals.css'
import { Noto_Sans_KR } from 'next/font/google'

const notoSansKR = Noto_Sans_KR({
  weight: ['300', '400', '500', '700'],
  display: 'swap',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Rating - топ ресурсов',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={notoSansKR.className}>{children}</body>
    </html>
  )
}
